ALTER TABLE order_item
    DROP CONSTRAINT FK_ORDER_ITEM_ON_ORDER,
    MODIFY id INT AUTO_INCREMENT;

ALTER TABLE `order`
    MODIFY id INT AUTO_INCREMENT;

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES `order` (id);